Metrics/MethodLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false  

Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false